In [1]:
import gzip
import re
from collections import Counter, defaultdict
from pathlib import Path

import polars as pl

DATA = Path("../../skos")

cfg = pl.Config(tbl_rows=-1, tbl_cols=-1, fmt_str_lengths=10000, tbl_width_chars=10000, tbl_hide_dataframe_shape=True)

In [2]:
PREFIXES = {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "skosxl": "http://www.w3.org/2008/05/skos-xl#",
    "dcterms": "http://purl.org/dc/terms/",
    "dc": "http://purl.org/dc/elements/1.1/",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "prov": "http://www.w3.org/ns/prov#",
    "vann": "http://purl.org/vocab/vann/",
    "void": "http://rdfs.org/ns/void#",
    "schema": "http://schema.org/",
    "euvoc": "http://publications.europa.eu/ontology/euvoc#",
    "at": "http://publications.europa.eu/ontology/authority/",
    "gn": "https://www.geonames.org/ontology#",
    "zbwext": "http://zbw.eu/namespaces/zbw-extensions/",
    "unesco": "http://vocabularies.unesco.org/ontology#",
    "gemet": "http://www.eionet.europa.eu/gemet/2004/06/gemet-schema.rdf#",
    "physh": "https://physh.org/rdf/2018/01/01/core#",
    "locn": "https://www.w3.org/ns/locn#",
    "cs": "http://purl.org/vocab/changeset/schema#",
    "iso-thes": "http://purl.org/iso25964/skos-thes#",
    "lexinfo": "http://www.lexinfo.net/ontology/2.0/lexinfo#",
    "xkos": "http://rdf-vocabulary.ddialliance.org/xkos#",
}
RDF_TYPE = "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>"
SUBCLASS_OF = "<http://www.w3.org/2000/01/rdf-schema#subClassOf>"
TERM = re.compile(r'<[^>]*>|_:\S+|"(?:[^"\\]|\\.)*"(?:@[\w-]+|\^\^<[^>]*>)?')
LITERAL = re.compile(r'"(?:[^"\\]|\\.)*"(?:@([\w-]+)|\^\^(<[^>]*>))?')


def short(term):
    if not term.startswith("<"):
        return term
    iri = term[1:-1]
    for prefix, ns in PREFIXES.items():
        if iri.startswith(ns):
            return f"{prefix}:{iri[len(ns):]}"
    return term


def literal_type(term):
    lang, dt = LITERAL.fullmatch(term).groups()
    return "rdf:langString" if lang else short(dt) if dt else "xsd:string"


def triples(path):
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            if line.strip() and not line.startswith("#"):
                yield tuple(TERM.findall(line)[:3])

In [3]:
def stats(path):
    ts = set(triples(path))
    types = defaultdict(set)
    for s, p, o in ts:
        if p == RDF_TYPE:
            types[s].add(o)
    class_uses = Counter(o for _, p, o in ts if p == RDF_TYPE)
    supers = defaultdict(set)
    for s, p, o in ts:
        if p == SUBCLASS_OF and s in class_uses:
            supers[s].add(o)
    untyped = {"(untyped)"}
    prop_uses, domains, ranges = Counter(), defaultdict(set), defaultdict(set)
    for s, p, o in ts:
        prop_uses[p] += 1
        domains[p] |= types.get(s, untyped)
        if o.startswith('"'):
            ranges[p].add(literal_type(o))
        else:
            ranges[p] |= types.get(o, untyped)
    names = lambda xs: sorted(short(x) for x in xs)
    classes = [
        {"class": short(c), "uses": n, "subClassOf": names(supers[c])}
        for c, n in class_uses.items()
    ]
    props = [
        {"property": short(p), "uses": n, "domains": names(domains[p]), "ranges": names(ranges[p])}
        for p, n in prop_uses.items()
    ]
    return len(ts), classes, props


datasets = sorted(d.name for d in DATA.iterdir() if (d / "main.nt.gz").exists())
overview, class_rows, prop_rows = [], [], []
for name in datasets:
    n, classes, props = stats(DATA / name / "main.nt.gz")
    overview.append({"dataset": name, "triples": n, "classes": len(classes), "properties": len(props)})
    class_rows += [{"dataset": name, **r} for r in classes]
    prop_rows += [{"dataset": name, **r} for r in props]

overview = pl.DataFrame(overview)
classes = pl.DataFrame(class_rows, schema_overrides={"subClassOf": pl.List(pl.String)})
props = pl.DataFrame(prop_rows)

In [4]:
def joined(df):
    return df.with_columns(pl.col(pl.List(pl.String)).list.join(", "))


overview.sort("triples", descending=True)

┌─────────────────────┬─────────┬─────────┬────────────┐
│ dataset             ┆ triples ┆ classes ┆ properties │
│ ---                 ┆ ---     ┆ ---     ┆ ---        │
│ str                 ┆ i64     ┆ i64     ┆ i64        │
╞═════════════════════╪═════════╪═════════╪════════════╡
│ eu-nuts-2021        ┆ 383781  ┆ 11      ┆ 65         │
│ gemet               ┆ 323635  ┆ 7       ┆ 34         │
│ eu-cpv              ┆ 264759  ┆ 2       ┆ 7          │
│ stw-economics       ┆ 120694  ┆ 15      ┆ 65         │
│ eu-nace-rev2        ┆ 120439  ┆ 7       ┆ 53         │
│ eu-languages        ┆ 116190  ┆ 3       ┆ 21         │
│ unesco-thesaurus    ┆ 99711   ┆ 6       ┆ 38         │
│ loc-genre-form      ┆ 76520   ┆ 3       ┆ 18         │
│ nerc-p06-units      ┆ 65529   ┆ 2       ┆ 33         │
│ uat-astronomy       ┆ 24434   ┆ 2       ┆ 24         │
│ physh               ┆ 23863   ┆ 5       ┆ 24         │
│ iptc-media-topics   ┆ 16971   ┆ 2       ┆ 25         │
│ geonames-ontology   ┆ 6844    ┆ 11      ┆ 41         │
│ coar-resource-types ┆ 4726    ┆ 3       ┆ 21         │
│ loc-relators        ┆ 1779    ┆ 2       ┆ 12         │
│ inspire-themes      ┆ 1642    ┆ 6       ┆ 31         │
│ eu-data-theme       ┆ 491     ┆ 2       ┆ 14         │
└─────────────────────┴─────────┴─────────┴────────────┘

In [5]:
joined(
    classes.group_by("class")
    .agg(
        pl.col("uses").sum(),
        pl.col("dataset").n_unique().alias("datasets"),
        pl.col("subClassOf").list.explode(keep_nulls=False, empty_as_null=False).unique().sort(),
    )
    .sort("uses", descending=True)
)

┌────────────────────────────────────────┬───────┬──────────┬────────────────────┐
│ class                                  ┆ uses  ┆ datasets ┆ subClassOf         │
│ ---                                    ┆ ---   ┆ ---      ┆ ---                │
│ str                                    ┆ i64   ┆ u32      ┆ str                │
╞════════════════════════════════════════╪═══════╪══════════╪════════════════════╡
│ skos:Concept                           ┆ 49853 ┆ 16       ┆                    │
│ locn:Geometry                          ┆ 27660 ┆ 1        ┆                    │
│ dcat:Distribution                      ┆ 27660 ┆ 1        ┆                    │
│ at:MappedCode                          ┆ 9325  ┆ 1        ┆                    │
│ skosxl:Label                           ┆ 9073  ┆ 3        ┆                    │
│ zbwext:Descriptor                      ┆ 7253  ┆ 1        ┆ skos:Concept       │
│ xkos:ConceptAssociation                ┆ 6606  ┆ 2        ┆                    │
│ cs:ChangeSet                           ┆ 5740  ┆ 1        ┆                    │
│ euvoc:XlNotation                       ┆ 2485  ┆ 1        ┆                    │
│ gn:Code                                ┆ 690   ┆ 1        ┆ skos:Concept       │
│ zbwext:Thsys                           ┆ 592   ┆ 1        ┆ skos:Concept       │
│ physh:Concept                          ┆ 568   ┆ 1        ┆                    │
│ skos:Collection                        ┆ 329   ┆ 6        ┆                    │
│ iso-thes:ConceptGroup                  ┆ 95    ┆ 1        ┆                    │
│ unesco:MicroThesaurus                  ┆ 88    ┆ 1        ┆                    │
│ gemet:Source                           ┆ 87    ┆ 1        ┆                    │
│ owl:ObjectProperty                     ┆ 41    ┆ 2        ┆                    │
│ gemet:Theme                            ┆ 40    ┆ 1        ┆                    │
│ skos:ConceptScheme                     ┆ 36    ┆ 13       ┆                    │
│ gemet:Group                            ┆ 32    ┆ 1        ┆                    │
│ rdf:Property                           ┆ 28    ┆ 1        ┆                    │
│ owl:Class                              ┆ 20    ┆ 2        ┆                    │
│ physh:Discipline                       ┆ 19    ┆ 1        ┆                    │
│ xkos:Correspondence                    ┆ 17    ┆ 2        ┆                    │
│ owl:Restriction                        ┆ 16    ┆ 1        ┆                    │
│ owl:DatatypeProperty                   ┆ 15    ┆ 2        ┆                    │
│ owl:AnnotationProperty                 ┆ 13    ┆ 1        ┆                    │
│ physh:Facet                            ┆ 9     ┆ 1        ┆                    │
│ gn:Class                               ┆ 9     ┆ 1        ┆ skos:ConceptScheme │
│ xkos:ClassificationLevel               ┆ 8     ┆ 2        ┆                    │
│ unesco:Domain                          ┆ 7     ┆ 1        ┆                    │
│ owl:FunctionalProperty                 ┆ 7     ┆ 1        ┆                    │
│ owl:SymmetricProperty                  ┆ 5     ┆ 2        ┆                    │
│ gemet:SuperGroup                       ┆ 4     ┆ 1        ┆                    │
│ owl:TransitiveProperty                 ┆ 4     ┆ 2        ┆                    │
│ owl:Ontology                           ┆ 3     ┆ 3        ┆                    │
│ foaf:Agent                             ┆ 3     ┆ 1        ┆                    │
│ dcat:Catalog                           ┆ 2     ┆ 1        ┆                    │
│ foaf:Person                            ┆ 1     ┆ 1        ┆                    │
│ skos:OrderedCollection                 ┆ 1     ┆ 1        ┆                    │
│ owl:InverseFunctionalProperty          ┆ 1     ┆ 1        ┆                    │
│ void:Dataset                           ┆ 1     ┆ 1        ┆                    │
│ foaf:Organization                      ┆ 1     ┆ 1        ┆                    │
│ <http://www.w3.org/2006/vcard/ns#Kind> ┆ 1     ┆ 1        ┆                    │
│ dcat:Dataset                           ┆ 1     ┆ 1        ┆                    │
└────────────────────────────────────────┴───────┴──────────┴────────────────────┘

In [6]:
for name in datasets:
    print(name)
    display(joined(classes.filter(pl.col("dataset") == name).drop("dataset").sort("uses", descending=True)))

coar-resource-types

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 110  ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
│ skos:Collection    ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

eu-cpv

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 9454 ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

eu-data-theme

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 14   ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

eu-languages

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ at:MappedCode      ┆ 9325 ┆            │
│ skos:Concept       ┆ 7742 ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

eu-nace-rev2

┌──────────────────────────┬──────┬────────────┐
│ class                    ┆ uses ┆ subClassOf │
│ ---                      ┆ ---  ┆ ---        │
│ str                      ┆ i64  ┆ str        │
╞══════════════════════════╪══════╪════════════╡
│ xkos:ConceptAssociation  ┆ 5693 ┆            │
│ skos:Concept             ┆ 996  ┆            │
│ skos:Collection          ┆ 150  ┆            │
│ xkos:Correspondence      ┆ 11   ┆            │
│ xkos:ClassificationLevel ┆ 4    ┆            │
│ skos:OrderedCollection   ┆ 1    ┆            │
│ skos:ConceptScheme       ┆ 1    ┆            │
└──────────────────────────┴──────┴────────────┘

eu-nuts-2021

┌──────────────────────────┬───────┬────────────┐
│ class                    ┆ uses  ┆ subClassOf │
│ ---                      ┆ ---   ┆ ---        │
│ str                      ┆ i64   ┆ str        │
╞══════════════════════════╪═══════╪════════════╡
│ dcat:Distribution        ┆ 27660 ┆            │
│ locn:Geometry            ┆ 27660 ┆            │
│ skosxl:Label             ┆ 2702  ┆            │
│ skos:Concept             ┆ 2526  ┆            │
│ euvoc:XlNotation         ┆ 2485  ┆            │
│ xkos:ConceptAssociation  ┆ 913   ┆            │
│ xkos:Correspondence      ┆ 6     ┆            │
│ skos:ConceptScheme       ┆ 6     ┆            │
│ xkos:ClassificationLevel ┆ 4     ┆            │
│ skos:Collection          ┆ 4     ┆            │
│ owl:Ontology             ┆ 1     ┆            │
└──────────────────────────┴───────┴────────────┘

gemet

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 5573 ┆            │
│ gemet:Source       ┆ 87   ┆            │
│ skos:Collection    ┆ 78   ┆            │
│ gemet:Theme        ┆ 40   ┆            │
│ gemet:Group        ┆ 32   ┆            │
│ gemet:SuperGroup   ┆ 4    ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

geonames-ontology

┌────────────────────────┬──────┬────────────────────┐
│ class                  ┆ uses ┆ subClassOf         │
│ ---                    ┆ ---  ┆ ---                │
│ str                    ┆ i64  ┆ str                │
╞════════════════════════╪══════╪════════════════════╡
│ gn:Code                ┆ 690  ┆ skos:Concept       │
│ owl:Restriction        ┆ 16   ┆                    │
│ owl:ObjectProperty     ┆ 16   ┆                    │
│ owl:DatatypeProperty   ┆ 14   ┆                    │
│ gn:Class               ┆ 9    ┆ skos:ConceptScheme │
│ owl:Class              ┆ 7    ┆                    │
│ owl:SymmetricProperty  ┆ 1    ┆                    │
│ owl:TransitiveProperty ┆ 1    ┆                    │
│ owl:Ontology           ┆ 1    ┆                    │
│ foaf:Person            ┆ 1    ┆                    │
│ foaf:Organization      ┆ 1    ┆                    │
└────────────────────────┴──────┴────────────────────┘

inspire-themes

┌────────────────────────────────────────┬──────┬────────────┐
│ class                                  ┆ uses ┆ subClassOf │
│ ---                                    ┆ ---  ┆ ---        │
│ str                                    ┆ i64  ┆ str        │
╞════════════════════════════════════════╪══════╪════════════╡
│ skos:Concept                           ┆ 35   ┆            │
│ foaf:Agent                             ┆ 3    ┆            │
│ dcat:Catalog                           ┆ 2    ┆            │
│ dcat:Dataset                           ┆ 1    ┆            │
│ skos:ConceptScheme                     ┆ 1    ┆            │
│ <http://www.w3.org/2006/vcard/ns#Kind> ┆ 1    ┆            │
└────────────────────────────────────────┴──────┴────────────┘

iptc-media-topics

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 1393 ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

loc-genre-form

┌──────────────┬──────┬────────────┐
│ class        ┆ uses ┆ subClassOf │
│ ---          ┆ ---  ┆ ---        │
│ str          ┆ i64  ┆ str        │
╞══════════════╪══════╪════════════╡
│ skosxl:Label ┆ 6314 ┆            │
│ cs:ChangeSet ┆ 5740 ┆            │
│ skos:Concept ┆ 2685 ┆            │
└──────────────┴──────┴────────────┘

loc-relators

┌──────────────┬──────┬────────────┐
│ class        ┆ uses ┆ subClassOf │
│ ---          ┆ ---  ┆ ---        │
│ str          ┆ i64  ┆ str        │
╞══════════════╪══════╪════════════╡
│ skos:Concept ┆ 268  ┆            │
│ skosxl:Label ┆ 57   ┆            │
└──────────────┴──────┴────────────┘

nerc-p06-units

┌─────────────────┬──────┬────────────┐
│ class           ┆ uses ┆ subClassOf │
│ ---             ┆ ---  ┆ ---        │
│ str             ┆ i64  ┆ str        │
╞═════════════════╪══════╪════════════╡
│ skos:Concept    ┆ 410  ┆            │
│ skos:Collection ┆ 1    ┆            │
└─────────────────┴──────┴────────────┘

physh

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 3891 ┆            │
│ physh:Concept      ┆ 568  ┆            │
│ physh:Discipline   ┆ 19   ┆            │
│ skos:ConceptScheme ┆ 19   ┆            │
│ physh:Facet        ┆ 9    ┆            │
└────────────────────┴──────┴────────────┘

stw-economics

┌───────────────────────────────┬──────┬──────────────┐
│ class                         ┆ uses ┆ subClassOf   │
│ ---                           ┆ ---  ┆ ---          │
│ str                           ┆ i64  ┆ str          │
╞═══════════════════════════════╪══════╪══════════════╡
│ skos:Concept                  ┆ 7845 ┆              │
│ zbwext:Descriptor             ┆ 7253 ┆ skos:Concept │
│ zbwext:Thsys                  ┆ 592  ┆ skos:Concept │
│ rdf:Property                  ┆ 28   ┆              │
│ owl:ObjectProperty            ┆ 25   ┆              │
│ owl:AnnotationProperty        ┆ 13   ┆              │
│ owl:Class                     ┆ 13   ┆              │
│ owl:FunctionalProperty        ┆ 7    ┆              │
│ owl:SymmetricProperty         ┆ 4    ┆              │
│ owl:TransitiveProperty        ┆ 3    ┆              │
│ owl:DatatypeProperty          ┆ 1    ┆              │
│ owl:Ontology                  ┆ 1    ┆              │
│ owl:InverseFunctionalProperty ┆ 1    ┆              │
│ void:Dataset                  ┆ 1    ┆              │
│ skos:ConceptScheme            ┆ 1    ┆              │
└───────────────────────────────┴──────┴──────────────┘

uat-astronomy

┌────────────────────┬──────┬────────────┐
│ class              ┆ uses ┆ subClassOf │
│ ---                ┆ ---  ┆ ---        │
│ str                ┆ i64  ┆ str        │
╞════════════════════╪══════╪════════════╡
│ skos:Concept       ┆ 2411 ┆            │
│ skos:ConceptScheme ┆ 1    ┆            │
└────────────────────┴──────┴────────────┘

unesco-thesaurus

┌───────────────────────┬──────┬────────────┐
│ class                 ┆ uses ┆ subClassOf │
│ ---                   ┆ ---  ┆ ---        │
│ str                   ┆ i64  ┆ str        │
╞═══════════════════════╪══════╪════════════╡
│ skos:Concept          ┆ 4500 ┆            │
│ iso-thes:ConceptGroup ┆ 95   ┆            │
│ skos:Collection       ┆ 95   ┆            │
│ unesco:MicroThesaurus ┆ 88   ┆            │
│ unesco:Domain         ┆ 7    ┆            │
│ skos:ConceptScheme    ┆ 1    ┆            │
└───────────────────────┴──────┴────────────┘

In [7]:
joined(
    props.group_by("property")
    .agg(
        pl.col("uses").sum(),
        pl.col("dataset").n_unique().alias("datasets"),
        pl.col("domains").list.explode(keep_nulls=False, empty_as_null=False).unique().sort(),
        pl.col("ranges").list.explode(keep_nulls=False, empty_as_null=False).unique().sort(),
    )
    .sort("uses", descending=True)
)

┌────────────────────────────────────────────────────────────┬────────┬──────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ property                                                   ┆ uses   ┆ datasets ┆ domains                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ┆ ranges                                                                                                                                   │
│ ---                                                        ┆ ---    ┆ ---      ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ┆ ---                                                                                                                                      │
│ str                                                        ┆ i64    ┆ u32      ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ┆ str                                                                                                                                      │
╞════════════════════════════════════════════════════════════╪════════╪══════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ skos:prefLabel                                             ┆ 525591 ┆ 17       ┆ dcat:Catalog, dcat:Dataset, gemet:Group, gemet:SuperGroup, gn:Code, iso-thes:ConceptGroup, physh:Concept, physh:Facet, skos:Collection, skos:Concept, skos:ConceptScheme, skos:OrderedCollection, unesco:Domain, unesco:MicroThesaurus, void:Dataset, xkos:ClassificationLevel, xkos:Correspondence, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ┆ rdf:langString, xsd:string                                                                                                               │
│ rdf:type                                                   ┆ 148449 ┆ 17       ┆ <http://www.w3.org/2006/vcard/ns#Kind>, at:MappedCode, cs:ChangeSet, dcat:Catalog, dcat:Dataset, dcat:Distribution, euvoc:XlNotation, foaf:Agent, foaf:Organization, foaf:Person, gemet:Group, gemet:Source, gemet:SuperGroup, gemet:Theme, gn:Class, gn:Code, iso-thes:ConceptGroup, locn:Geometry, owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty, owl:ObjectProperty, owl:Ontology, owl:Restriction, owl:SymmetricProperty, owl:TransitiveProperty, physh:Concept, physh:Discipline, physh:Facet, rdf:Property, skos:Collection, skos:Concept, skos:ConceptScheme, skos:OrderedCollection, skosxl:Label, unesco:Domain, unesco:MicroThesaurus, void:Dataset, xkos:ClassificationLevel, xkos:ConceptAssociation, xkos:Correspondence, zbwext:Descriptor, zbwext:Thsys ┆ (untyped), owl:Class                                                                                                                     │
│ skos:related                                               ┆ 90276  ┆ 7        ┆ physh:Concept, skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ┆ (untyped), physh:Concept, skos:Concept, zbwext:Descriptor                                                                                │
│ skos:altLabel                                              ┆ 83182  ┆ 11       ┆ (untyped), iso-thes:ConceptGroup, physh:Concept, skos:Collection, skos:Concept, skos:ConceptScheme, unesco:MicroThesaurus, zbwext:Descriptor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ┆ rdf:langString, xsd:string                                                                                                               │
│ skos:note                                                  ┆ 57036  ┆ 5        ┆ dcat:Distribution, skos:Concept, skos:ConceptScheme, skosxl:Label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ┆ rdf:langString, xsd:string                                                                                                               │
│ skos:inScheme                                              ┆ 51235  ┆ 15       ┆ (untyped), dcat:Catalog, dcat:Dataset, gemet:Group, gemet:SuperGroup, gemet:Theme, gn:Code, iso-thes:ConceptGroup, skos:Collection, skos:Concept, skos:ConceptScheme, unesco:Domain, unesco:MicroThesaurus, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ┆ (untyped), dcat:Catalog, dcat:Dataset, gn:Class, skos:ConceptScheme, void:Dataset                                                        │
│ skos:definition                                            ┆ 50710  ┆ 10       ┆ dcat:Catalog, dcat:Dataset, gn:Code, owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property, skos:Concept, skos:ConceptScheme                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ┆ (untyped), rdf:langString, xsd:string                                                                                                    │
│ skos:broader                                               ┆ 48841  ┆ 13       ┆ physh:Concept, physh:Facet, skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ┆ (untyped), physh:Concept, physh:Facet, skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                     │
│ skos:narrower                                              ┆ 38212  ┆ 10       ┆ physh:Concept, physh:Facet, skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ┆ physh:Concept, physh:Facet, skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                │
│ dcterms:format                                             ┆ 27878  ┆ 3        ┆ (untyped), dcat:Catalog, dcat:Dataset, dcat:Distribution, skos:ConceptScheme                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ┆ (untyped)                                                                                                                                │
│ dcterms:license                                            ┆ 27662  ┆ 3        ┆ dcat:Distribution, skos:Collection, skos:ConceptScheme                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ┆ (untyped)                                                                                                                                │
│ <http://data.europa.eu/nuts/scale>                         ┆ 27660  ┆ 1        ┆ locn:Geometry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ┆ xsd:string                                                                                                                               │
│ locn:geometry                                              ┆ 27660  ┆ 1        ┆ skos:Concept                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ┆ locn:Geometry                                                                                                                            │
│ <http://data.europa.eu/nuts/projection>                    ┆ 27660  ┆ 1        ┆ locn:Geometry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ┆ xsd:string                                                                                                                               │

In [8]:
for name in datasets:
    print(name)
    display(joined(props.filter(pl.col("dataset") == name).drop("dataset").sort("uses", descending=True)))

coar-resource-types

┌─────────────────────────────────────────────────────┬──────┬───────────────────────────────────────────────────┬─────────────────────────┐
│ property                                            ┆ uses ┆ domains                                           ┆ ranges                  │
│ ---                                                 ┆ ---  ┆ ---                                               ┆ ---                     │
│ str                                                 ┆ i64  ┆ str                                               ┆ str                     │
╞═════════════════════════════════════════════════════╪══════╪═══════════════════════════════════════════════════╪═════════════════════════╡
│ skos:prefLabel                                      ┆ 2750 ┆ skos:Collection, skos:Concept                     ┆ rdf:langString          │
│ skos:altLabel                                       ┆ 1107 ┆ skos:Concept                                      ┆ rdf:langString          │
│ rdf:type                                            ┆ 112  ┆ skos:Collection, skos:Concept, skos:ConceptScheme ┆ (untyped)               │
│ skos:definition                                     ┆ 111  ┆ skos:Concept                                      ┆ rdf:langString          │
│ skos:inScheme                                       ┆ 110  ┆ skos:Concept                                      ┆ skos:ConceptScheme      │
│ skos:broadMatch                                     ┆ 91   ┆ skos:Concept                                      ┆ (untyped), skos:Concept │
│ skos:exactMatch                                     ┆ 88   ┆ skos:Concept                                      ┆ (untyped)               │
│ skos:narrower                                       ┆ 84   ┆ skos:Concept                                      ┆ skos:Concept            │
│ skos:broader                                        ┆ 84   ┆ skos:Concept                                      ┆ skos:Concept            │
│ skos:editorialNote                                  ┆ 45   ┆ skos:Concept                                      ┆ rdf:langString          │
│ skos:topConceptOf                                   ┆ 26   ┆ skos:Concept                                      ┆ skos:ConceptScheme      │
│ skos:hasTopConcept                                  ┆ 26   ┆ skos:ConceptScheme                                ┆ skos:Concept            │
│ skos:narrowMatch                                    ┆ 24   ┆ skos:Concept                                      ┆ (untyped)               │
│ dcterms:contributor                                 ┆ 21   ┆ skos:ConceptScheme                                ┆ xsd:string              │
│ dcterms:creator                                     ┆ 19   ┆ skos:ConceptScheme                                ┆ xsd:string              │
│ skos:relatedMatch                                   ┆ 16   ┆ skos:Concept                                      ┆ (untyped)               │
│ <http://purl.org/coar/resource_type/schema#expires> ┆ 8    ┆ skos:Concept                                      ┆ xsd:string              │
│ dcterms:title                                       ┆ 1    ┆ skos:ConceptScheme                                ┆ xsd:string              │
│ dcterms:modified                                    ┆ 1    ┆ skos:ConceptScheme                                ┆ xsd:dateTime            │
│ rdfs:label                                          ┆ 1    ┆ skos:ConceptScheme                                ┆ xsd:string              │
│ dcterms:description                                 ┆ 1    ┆ skos:ConceptScheme                                ┆ xsd:string              │
└─────────────────────────────────────────────────────┴──────┴───────────────────────────────────────────────────┴─────────────────────────┘

eu-cpv

┌────────────────────┬────────┬──────────────────────────────────┬────────────────────┐
│ property           ┆ uses   ┆ domains                          ┆ ranges             │
│ ---                ┆ ---    ┆ ---                              ┆ ---                │
│ str                ┆ i64    ┆ str                              ┆ str                │
╞════════════════════╪════════╪══════════════════════════════════╪════════════════════╡
│ skos:prefLabel     ┆ 226897 ┆ skos:Concept, skos:ConceptScheme ┆ rdf:langString     │
│ rdf:type           ┆ 9455   ┆ skos:Concept, skos:ConceptScheme ┆ (untyped)          │
│ skos:inScheme      ┆ 9454   ┆ skos:Concept                     ┆ skos:ConceptScheme │
│ skos:notation      ┆ 9454   ┆ skos:Concept                     ┆ xsd:string         │
│ skos:broader       ┆ 9409   ┆ skos:Concept                     ┆ skos:Concept       │
│ skos:topConceptOf  ┆ 45     ┆ skos:Concept                     ┆ skos:ConceptScheme │
│ skos:hasTopConcept ┆ 45     ┆ skos:ConceptScheme               ┆ skos:Concept       │
└────────────────────┴────────┴──────────────────────────────────┴────────────────────┘

eu-data-theme

┌────────────────────────────────────────────────────────────┬──────┬──────────────────────────────────┬────────────────────┐
│ property                                                   ┆ uses ┆ domains                          ┆ ranges             │
│ ---                                                        ┆ ---  ┆ ---                              ┆ ---                │
│ str                                                        ┆ i64  ┆ str                              ┆ str                │
╞════════════════════════════════════════════════════════════╪══════╪══════════════════════════════════╪════════════════════╡
│ skos:prefLabel                                             ┆ 376  ┆ skos:Concept, skos:ConceptScheme ┆ rdf:langString     │
│ rdf:type                                                   ┆ 15   ┆ skos:Concept, skos:ConceptScheme ┆ (untyped)          │
│ dc:identifier                                              ┆ 14   ┆ skos:Concept                     ┆ xsd:string         │
│ at:op-code                                                 ┆ 14   ┆ skos:Concept                     ┆ xsd:string         │
│ <http://publications.europa.eu/resource/authority/op-code> ┆ 14   ┆ skos:Concept                     ┆ xsd:string         │
│ skos:inScheme                                              ┆ 14   ┆ skos:Concept                     ┆ skos:ConceptScheme │
│ at:authority-code                                          ┆ 13   ┆ skos:Concept                     ┆ xsd:string         │
│ at:start.use                                               ┆ 13   ┆ skos:Concept                     ┆ xsd:string         │
│ at:deprecated                                              ┆ 13   ┆ skos:Concept                     ┆ xsd:string         │
│ owl:versionInfo                                            ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
│ rdfs:label                                                 ┆ 1    ┆ skos:ConceptScheme               ┆ rdf:langString     │
│ at:prefLabel                                               ┆ 1    ┆ skos:ConceptScheme               ┆ rdf:langString     │
│ at:table.id                                                ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
│ at:table.version.number                                    ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
└────────────────────────────────────────────────────────────┴──────┴──────────────────────────────────┴────────────────────┘

eu-languages

┌────────────────────────────────────────────────────────────┬───────┬─────────────────────────────────────────────────┬────────────────────┐
│ property                                                   ┆ uses  ┆ domains                                         ┆ ranges             │
│ ---                                                        ┆ ---   ┆ ---                                             ┆ ---                │
│ str                                                        ┆ i64   ┆ str                                             ┆ str                │
╞════════════════════════════════════════════════════════════╪═══════╪═════════════════════════════════════════════════╪════════════════════╡
│ rdf:type                                                   ┆ 17068 ┆ at:MappedCode, skos:Concept, skos:ConceptScheme ┆ (untyped)          │
│ skos:prefLabel                                             ┆ 16596 ┆ skos:Concept, skos:ConceptScheme                ┆ rdf:langString     │
│ dc:source                                                  ┆ 9325  ┆ at:MappedCode                                   ┆ xsd:string         │
│ at:op-mapped-code                                          ┆ 9325  ┆ skos:Concept                                    ┆ at:MappedCode      │
│ at:legacy-code                                             ┆ 9325  ┆ at:MappedCode                                   ┆ xsd:string         │
│ dc:identifier                                              ┆ 7742  ┆ skos:Concept                                    ┆ xsd:string         │
│ <http://publications.europa.eu/resource/authority/op-code> ┆ 7742  ┆ skos:Concept                                    ┆ xsd:string         │
│ skos:inScheme                                              ┆ 7742  ┆ skos:Concept                                    ┆ skos:ConceptScheme │
│ at:op-code                                                 ┆ 7742  ┆ skos:Concept                                    ┆ xsd:string         │
│ at:start.use                                               ┆ 7741  ┆ skos:Concept                                    ┆ xsd:string         │
│ at:authority-code                                          ┆ 7741  ┆ skos:Concept                                    ┆ xsd:string         │
│ at:deprecated                                              ┆ 7741  ┆ skos:Concept                                    ┆ xsd:string         │
│ at:affected-table                                          ┆ 303   ┆ at:MappedCode                                   ┆ xsd:string         │
│ at:protocol-order                                          ┆ 24    ┆ skos:Concept                                    ┆ xsd:string         │
│ at:protocol.order                                          ┆ 24    ┆ skos:Concept                                    ┆ xsd:string         │
│ at:end.use                                                 ┆ 4     ┆ skos:Concept                                    ┆ xsd:string         │
│ at:table.id                                                ┆ 1     ┆ skos:ConceptScheme                              ┆ xsd:string         │
│ rdfs:label                                                 ┆ 1     ┆ skos:ConceptScheme                              ┆ rdf:langString     │
│ owl:versionInfo                                            ┆ 1     ┆ skos:ConceptScheme                              ┆ xsd:string         │
│ at:table.version.number                                    ┆ 1     ┆ skos:ConceptScheme                              ┆ xsd:string         │
│ at:prefLabel                                               ┆ 1     ┆ skos:ConceptScheme                              ┆ rdf:langString     │
└────────────────────────────────────────────────────────────┴───────┴─────────────────────────────────────────────────┴────────────────────┘

eu-nace-rev2

┌───────────────────────────────────────────────────┬───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ property                                          ┆ uses  ┆ domains                                                                                                                                           ┆ ranges                                                                                                                   │
│ ---                                               ┆ ---   ┆ ---                                                                                                                                               ┆ ---                                                                                                                      │
│ str                                               ┆ i64   ┆ str                                                                                                                                               ┆ str                                                                                                                      │
╞═══════════════════════════════════════════════════╪═══════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ skos:prefLabel                                    ┆ 29150 ┆ skos:Collection, skos:Concept, skos:ConceptScheme, skos:OrderedCollection, xkos:ClassificationLevel, xkos:Correspondence                          ┆ rdf:langString                                                                                                           │
│ skos:altLabel                                     ┆ 25892 ┆ skos:Concept, skos:ConceptScheme                                                                                                                  ┆ rdf:langString                                                                                                           │
│ xkos:coreContentNote                              ┆ 8758  ┆ skos:Concept                                                                                                                                      ┆ rdf:langString                                                                                                           │
│ xkos:targetConcept                                ┆ 7705  ┆ xkos:ConceptAssociation                                                                                                                           ┆ (untyped)                                                                                                                │
│ rdf:type                                          ┆ 6856  ┆ skos:Collection, skos:Concept, skos:ConceptScheme, skos:OrderedCollection, xkos:ClassificationLevel, xkos:ConceptAssociation, xkos:Correspondence ┆ (untyped)                                                                                                                │
│ xkos:madeOf                                       ┆ 5693  ┆ xkos:Correspondence                                                                                                                               ┆ xkos:ConceptAssociation                                                                                                  │
│ xkos:sourceConcept                                ┆ 5692  ┆ xkos:ConceptAssociation                                                                                                                           ┆ (untyped), skos:Concept                                                                                                  │
│ xkos:exclusionNote                                ┆ 5671  ┆ skos:Concept                                                                                                                                      ┆ rdf:langString                                                                                                           │
│ skos:relatedMatch                                 ┆ 4172  ┆ (untyped), skos:Concept                                                                                                                           ┆ (untyped)                                                                                                                │
│ skos:closeMatch                                   ┆ 2585  ┆ skos:Concept                                                                                                                                      ┆ (untyped)                                                                                                                │
│ xkos:additionalContentNote                        ┆ 2081  ┆ skos:Concept                                                                                                                                      ┆ rdf:langString                                                                                                           │
│ <http://www.w3.org/ns/adms#identifier>            ┆ 1992  ┆ skos:Concept                                                                                                                                      ┆ <http://data.europa.eu/3yv/estat_concept/nace_r2>, <http://publications.europa.eu/resource/authority/notation-type/SDMX> │
│ skos:scopeNote                                    ┆ 1910  ┆ skos:Collection, xkos:ConceptAssociation                                                                                                          ┆ rdf:langString                                                                                                           │
│ dcterms:relation                                  ┆ 1793  ┆ skos:Collection, xkos:ConceptAssociation                                                                                                          ┆ <http://data.europa.eu/2en/class-series/NAICS2017>, xkos:Correspondence                                                  │
│ skos:member                                       ┆ 1524  ┆ (untyped), skos:Collection, xkos:ClassificationLevel                                                                                              ┆ (untyped), skos:Collection, skos:Concept                                                                                 │
│ skos:notation                                     ┆ 1137  ┆ skos:Collection, skos:Concept, skos:ConceptScheme                                                                                                 ┆ rdf:PlainLitera, xsd:string                                                                                              │
│ dcterms:description                               ┆ 998   ┆ skos:ConceptScheme, xkos:ConceptAssociation, xkos:Correspondence                                                                                  ┆ rdf:langString                                                                                                           │
│ <https://w3id.org/sssom/mapping_cardinality>      ┆ 996   ┆ xkos:ConceptAssociation                                                                                                                           ┆ (untyped)                                                                                                                │
│ skos:inScheme                                     ┆ 996   ┆ skos:Concept                                                                                                                                      ┆ skos:ConceptScheme                                                                                                       │
│ dc:identifier                                     ┆ 996   ┆ skos:Concept                                                                                                                                      ┆ xsd:string                                                                                                               │
│ dcterms:type                                      ┆ 996   ┆ xkos:ConceptAssociation                                                                                                                           ┆ xsd:string                                                                                                               │
│ <http://data.europa.eu/ux2/nace2/order>           ┆ 996   ┆ skos:Concept                                                                                                                                      ┆ xsd:integer                                                                                                              │
│ skos:broader                                      ┆ 975   ┆ skos:Concept                                                                                                                                      ┆ skos:Concept                                                                                                             │
│ xkos:caseLaw                                      ┆ 402   ┆ skos:Concept                                                                                                                                      ┆ rdf:langString                                                                                                           │
│ dcterms:modified                                  ┆ 221   ┆ skos:Collection, skos:Concept, skos:ConceptScheme, skos:OrderedCollection, xkos:ClassificationLevel, xkos:ConceptAssociation, xkos:Correspondence ┆ xsd:date                                                                                                                 │
│ dcterms:created                                   ┆ 73    ┆ skos:Collection, skos:ConceptScheme, skos:OrderedCollection, xkos:ConceptAssociation, xkos:Correspondence                                         ┆ xsd:date                                                                                                                 │
│ dcterms:language                                  ┆ 26    ┆ skos:ConceptScheme                                                                                                                                ┆ (untyped)                                                                                                                │
│ xkos:compares                                     ┆ 21    ┆ xkos:Correspondence                                                                                                                               ┆ (untyped), skos:ConceptScheme                                                                                            │
│ skos:hasTopConcept                                ┆ 21    ┆ skos:ConceptScheme                                                                                                                                ┆ skos:Concept                                                                                                             │
│ skos:topConceptOf                                 ┆ 21    ┆ skos:Concept                                                                                                                                      ┆ skos:ConceptScheme                                                                                                       │
│ dcterms:creator                                   ┆ 19    ┆ skos:Collection, skos:ConceptScheme, xkos:Correspondence                                                                                          ┆ (untyped)                                                                                                                │
│ rdf:first                                         ┆ 8     ┆ (untyped)                                                                                                                                         ┆ skos:Collection, xkos:ClassificationLevel                                                                                │
│ dcterms:isReferencedBy                            ┆ 8     ┆ skos:ConceptScheme                                                                                                                                ┆ (untyped), xkos:Correspondence                                                                                           │
│ rdf:rest                                          ┆ 8     ┆ (untyped)                                                                                                                                         ┆ (untyped)                                                                                                                │
│ <http://data.europa.eu/eli/ontology#based_on>     ┆ 7     ┆ skos:Collection, skos:ConceptScheme, xkos:Correspondence                                                                                          ┆ (untyped)                                                                                                                │
│ rdfs:seeAlso                                      ┆ 5     ┆ xkos:Correspondence                                                                                                                               ┆ (untyped)                                                                                                                │
│ rdfs:comment                                      ┆ 4     ┆ skos:Collection, xkos:ClassificationLevel                                                                                                         ┆ rdf:langString                                                                                                           │
│ xkos:organizedBy                                  ┆ 4     ┆ skos:Collection, xkos:ClassificationLevel                                                                                                         ┆ (untyped)                                                                                                                │
│ xkos:levels                                       ┆ 4     ┆ skos:ConceptScheme                                                                                                                                ┆ skos:Collection, xkos:ClassificationLevel                                                                                │
│ xkos:depth                                        ┆ 4     ┆ skos:Collection, xkos:ClassificationLevel                                                                                                         ┆ xsd:positiveInteger                                                                                                      │
│ xkos:covers                                       ┆ 4     ┆ skos:ConceptScheme                                                                                                                                ┆ (untyped)                                                                                                                │
│ xkos:notationPattern                              ┆ 4     ┆ skos:Collection, xkos:ClassificationLevel                                                                                                         ┆ xsd:string                                                                                                               │
│ xkos:numberOfLevels                               ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:positiveInteger                                                                                                      │
│ dcterms:source                                    ┆ 1     ┆ skos:Collection                                                                                                                                   ┆ rdf:PlainLiteral                                                                                                         │
│ <http://data.europa.eu/eli/ontology#version_date> ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:date                                                                                                                 │
│ schema:startDate                                  ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:date                                                                                                                 │
│ dcterms:issued                                    ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:date                                                                                                                 │
│ skos:memberList                                   ┆ 1     ┆ skos:OrderedCollection                                                                                                                            ┆ (untyped)                                                                                                                │
│ dcterms:references                                ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ rdf:PlainLiteral                                                                                                         │
│ owl:versionInfo                                   ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:string                                                                                                               │
│ xkos:belongsTo                                    ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ (untyped)                                                                                                                │
│ schema:endDate                                    ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:date                                                                                                                 │
│ dcterms:identifier                                ┆ 1     ┆ skos:ConceptScheme                                                                                                                                ┆ xsd:string                                                                                                               │
└───────────────────────────────────────────────────┴───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

eu-nuts-2021

┌──────────────────────────────────────────────────────────┬───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────┐
│ property                                                 ┆ uses  ┆ domains                                                                                                                                                                                                   ┆ ranges                                    │
│ ---                                                      ┆ ---   ┆ ---                                                                                                                                                                                                       ┆ ---                                       │
│ str                                                      ┆ i64   ┆ str                                                                                                                                                                                                       ┆ str                                       │
╞══════════════════════════════════════════════════════════╪═══════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════════════════════════════════════╡
│ rdf:type                                                 ┆ 63967 ┆ dcat:Distribution, euvoc:XlNotation, locn:Geometry, owl:Ontology, skos:Collection, skos:Concept, skos:ConceptScheme, skosxl:Label, xkos:ClassificationLevel, xkos:ConceptAssociation, xkos:Correspondence ┆ (untyped)                                 │
│ skos:note                                                ┆ 55320 ┆ dcat:Distribution                                                                                                                                                                                         ┆ xsd:string                                │
│ locn:geometry                                            ┆ 27660 ┆ skos:Concept                                                                                                                                                                                              ┆ locn:Geometry                             │
│ <http://data.europa.eu/nuts/projection>                  ┆ 27660 ┆ locn:Geometry                                                                                                                                                                                             ┆ xsd:string                                │
│ dcat:distribution                                        ┆ 27660 ┆ locn:Geometry                                                                                                                                                                                             ┆ dcat:Distribution                         │
│ dcat:downloadURL                                         ┆ 27660 ┆ dcat:Distribution                                                                                                                                                                                         ┆ xsd:string                                │
│ dcterms:format                                           ┆ 27660 ┆ dcat:Distribution                                                                                                                                                                                         ┆ (untyped)                                 │
│ dcterms:license                                          ┆ 27660 ┆ dcat:Distribution                                                                                                                                                                                         ┆ (untyped)                                 │
│ <http://data.europa.eu/nuts/scale>                       ┆ 27660 ┆ locn:Geometry                                                                                                                                                                                             ┆ xsd:string                                │
│ skos:inScheme                                            ┆ 9712  ┆ skos:Concept                                                                                                                                                                                              ┆ skos:ConceptScheme                        │
│ owl:versionInfo                                          ┆ 6131  ┆ skos:Concept, skos:ConceptScheme, skosxl:Label                                                                                                                                                            ┆ xsd:string                                │
│ skosxl:literalForm                                       ┆ 2702  ┆ skosxl:Label                                                                                                                                                                                              ┆ rdf:langString, xsd:string                │
│ skos:prefLabel                                           ┆ 2538  ┆ skos:Concept, skos:ConceptScheme, xkos:Correspondence                                                                                                                                                     ┆ rdf:langString, xsd:string                │
│ skosxl:prefLabel                                         ┆ 2536  ┆ skos:Collection, skos:Concept, skos:ConceptScheme, xkos:ClassificationLevel                                                                                                                               ┆ skosxl:Label                              │
│ skos:broader                                             ┆ 2530  ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ skos:narrower                                            ┆ 2530  ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ dc:identifier                                            ┆ 2526  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://www.w3.org/ns/adms#status>                       ┆ 2523  ┆ skos:Concept                                                                                                                                                                                              ┆ (untyped)                                 │
│ rdf:value                                                ┆ 2485  ┆ euvoc:XlNotation                                                                                                                                                                                          ┆ xsd:string                                │
│ euvoc:xlNotation                                         ┆ 2485  ┆ skos:Concept                                                                                                                                                                                              ┆ euvoc:XlNotation                          │
│ <http://data.europa.eu/nuts/level>                       ┆ 2385  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:decimal, xsd:string                   │
│ skos:notation                                            ┆ 2208  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ skos:member                                              ┆ 2067  ┆ skos:Collection, xkos:ClassificationLevel                                                                                                                                                                 ┆ skos:Concept                              │
│ <http://data.europa.eu/nuts/countryOrder>                ┆ 1844  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/regionOrder>                 ┆ 1844  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/metroStatus>                 ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:boolean                               │
│ <http://data.europa.eu/nuts/costalCategory>              ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/urbanRuralRemotnessCategory> ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/mountainCategory>            ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/mountainLabel>               ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://data.europa.eu/nuts/urbanRuralLabel>             ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://data.europa.eu/nuts/borderLabel>                 ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://data.europa.eu/nuts/urbanRuralCategory>          ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/costalLabel>                 ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://data.europa.eu/nuts/borderCategory>              ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:integer                               │
│ <http://data.europa.eu/nuts/urbanRuralRemotnessLabel>    ┆ 1345  ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ xkos:targetConcept                                       ┆ 942   ┆ xkos:ConceptAssociation                                                                                                                                                                                   ┆ skos:Concept                              │
│ rdfs:comment                                             ┆ 915   ┆ skos:ConceptScheme, xkos:ConceptAssociation                                                                                                                                                               ┆ rdf:PlainLiteral, rdf:langString          │
│ xkos:sourceConcept                                       ┆ 913   ┆ xkos:ConceptAssociation                                                                                                                                                                                   ┆ (untyped), skos:Concept                   │
│ xkos:madeOf                                              ┆ 912   ┆ xkos:Correspondence                                                                                                                                                                                       ┆ xkos:ConceptAssociation                   │
│ <http://data.europa.eu/nuts/metroCode>                   ┆ 565   ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://data.europa.eu/nuts/metroLabel>                  ┆ 565   ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:string                                │
│ dcterms:created                                          ┆ 564   ┆ skos:Concept, skos:ConceptScheme, skosxl:Label, xkos:ConceptAssociation, xkos:Correspondence                                                                                                              ┆ xsd:date, xsd:dateTime                    │
│ dcterms:replaces                                         ┆ 212   ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ dcterms:isReplacedBy                                     ┆ 212   ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ skosxl:altLabel                                          ┆ 166   ┆ skos:Concept                                                                                                                                                                                              ┆ skosxl:Label                              │
│ skos:hasTopConcept                                       ┆ 158   ┆ skos:ConceptScheme                                                                                                                                                                                        ┆ skos:Concept                              │
│ skos:topConceptOf                                        ┆ 158   ┆ skos:Concept                                                                                                                                                                                              ┆ skos:ConceptScheme                        │
│ <http://data.europa.eu/nuts/mergedFrom>                  ┆ 140   ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ <http://data.europa.eu/nuts/splitInto>                   ┆ 137   ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ lexinfo:romanization                                     ┆ 120   ┆ skosxl:Label                                                                                                                                                                                              ┆ xsd:string                                │
│ <http://data.europa.eu/nuts/mergedInto>                  ┆ 89    ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ <http://data.europa.eu/nuts/splitFrom>                   ┆ 86    ┆ skos:Concept                                                                                                                                                                                              ┆ skos:Concept                              │
│ <http://data.europa.eu/nuts/islandStatus>                ┆ 73    ┆ skos:Concept                                                                                                                                                                                              ┆ xsd:boolean                               │
│ dcterms:modified                                         ┆ 50    ┆ skos:Collection, skos:ConceptScheme, skosxl:Label, xkos:ClassificationLevel, xkos:ConceptAssociation, xkos:Correspondence                                                                                 ┆ xsd:dateTime                              │
│ xkos:levels                                              ┆ 20    ┆ skos:ConceptScheme                                                                                                                                                                                        ┆ skos:Collection, xkos:ClassificationLevel │
│ xkos:compares                                            ┆ 12    ┆ xkos:Correspondence                                                                                                                                                                                       ┆ skos:ConceptScheme                        │
│ xkos:belongsTo                                           ┆ 5     ┆ skos:ConceptScheme                                                                                                                                                                                        ┆ skos:ConceptScheme                        │

gemet

┌───────────────────────────┬────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────┐
│ property                  ┆ uses   ┆ domains                                                                                                     ┆ ranges                                                       │
│ ---                       ┆ ---    ┆ ---                                                                                                         ┆ ---                                                          │
│ str                       ┆ i64    ┆ str                                                                                                         ┆ str                                                          │
╞═══════════════════════════╪════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════╡
│ skos:prefLabel            ┆ 196661 ┆ gemet:Group, gemet:SuperGroup, skos:Collection, skos:Concept                                                ┆ rdf:langString                                               │
│ skos:definition           ┆ 46361  ┆ skos:Concept                                                                                                ┆ rdf:langString                                               │
│ skos:member               ┆ 16178  ┆ gemet:Group, gemet:SuperGroup, gemet:Theme, skos:Collection                                                 ┆ gemet:Group, gemet:SuperGroup, skos:Collection, skos:Concept │
│ rdf:type                  ┆ 5815   ┆ gemet:Group, gemet:Source, gemet:SuperGroup, gemet:Theme, skos:Collection, skos:Concept, skos:ConceptScheme ┆ (untyped)                                                    │
│ skos:narrower             ┆ 5689   ┆ skos:Concept                                                                                                ┆ skos:Concept                                                 │
│ skos:broader              ┆ 5685   ┆ skos:Concept                                                                                                ┆ skos:Concept                                                 │
│ skos:inScheme             ┆ 5651   ┆ gemet:Group, gemet:SuperGroup, gemet:Theme, skos:Collection, skos:Concept                                   ┆ skos:ConceptScheme                                           │
│ dcterms:created           ┆ 5649   ┆ gemet:Group, gemet:SuperGroup, gemet:Theme, skos:Collection, skos:Concept                                   ┆ xsd:dateTime                                                 │
│ dcterms:modified          ┆ 5649   ┆ gemet:Group, gemet:SuperGroup, gemet:Theme, skos:Collection, skos:Concept                                   ┆ xsd:dateTime                                                 │
│ skos:altLabel             ┆ 5598   ┆ skos:Concept                                                                                                ┆ rdf:langString                                               │
│ skos:closeMatch           ┆ 5522   ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ gemet:source              ┆ 4547   ┆ skos:Concept                                                                                                ┆ rdf:langString                                               │
│ skos:related              ┆ 3390   ┆ skos:Concept                                                                                                ┆ skos:Concept                                                 │
│ gemet:hasWikipediaArticle ┆ 3006   ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ skos:exactMatch           ┆ 2903   ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ rdfs:label                ┆ 1515   ┆ gemet:Source, gemet:Theme, skos:Collection, skos:ConceptScheme                                              ┆ rdf:langString, xsd:string                                   │
│ skos:relatedMatch         ┆ 972    ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ gemet:acronymLabel        ┆ 840    ┆ gemet:Theme, skos:Collection                                                                                ┆ rdf:langString                                               │
│ skos:editorialNote        ┆ 774    ┆ skos:Concept                                                                                                ┆ rdf:langString                                               │
│ skos:scopeNote            ┆ 362    ┆ skos:Concept                                                                                                ┆ rdf:langString                                               │
│ skos:broadMatch           ┆ 221    ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ skos:hasTopConcept        ┆ 112    ┆ skos:ConceptScheme                                                                                          ┆ skos:Concept                                                 │
│ skos:notation             ┆ 107    ┆ gemet:Source, skos:Concept                                                                                  ┆ rdf:langString, xsd:string                                   │
│ dcterms:issued            ┆ 87     ┆ gemet:Source                                                                                                ┆ xsd:string                                                   │
│ dcterms:title             ┆ 87     ┆ gemet:Source                                                                                                ┆ xsd:string                                                   │
│ dcterms:publisher         ┆ 85     ┆ gemet:Source                                                                                                ┆ xsd:string                                                   │
│ dcterms:creator           ┆ 72     ┆ gemet:Source                                                                                                ┆ xsd:string                                                   │
│ skos:narrowMatch          ┆ 40     ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ gemet:subGroupOf          ┆ 32     ┆ gemet:Group, skos:Collection                                                                                ┆ gemet:SuperGroup, skos:Collection                            │
│ skos:hiddenLabel          ┆ 17     ┆ skos:Concept                                                                                                ┆ rdf:langString                                               │
│ gemet:seeAlso             ┆ 5      ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
│ foaf:page                 ┆ 1      ┆ gemet:Source                                                                                                ┆ (untyped)                                                    │
│ dcterms:licence           ┆ 1      ┆ skos:ConceptScheme                                                                                          ┆ (untyped)                                                    │
│ gemet:sameEEAGlossary     ┆ 1      ┆ skos:Concept                                                                                                ┆ (untyped)                                                    │
└───────────────────────────┴────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────┘

geonames-ontology

┌──────────────────────────────────────────────────┬──────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────┐
│ property                                         ┆ uses ┆ domains                                                                                                                                                                              ┆ ranges                                                                      │
│ ---                                              ┆ ---  ┆ ---                                                                                                                                                                                  ┆ ---                                                                         │
│ str                                              ┆ i64  ┆ str                                                                                                                                                                                  ┆ str                                                                         │
╞══════════════════════════════════════════════════╪══════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════╡
│ skos:prefLabel                                   ┆ 3251 ┆ gn:Code                                                                                                                                                                              ┆ rdf:langString                                                              │
│ skos:definition                                  ┆ 1211 ┆ gn:Code                                                                                                                                                                              ┆ rdf:langString, xsd:string                                                  │
│ rdf:type                                         ┆ 757  ┆ foaf:Organization, foaf:Person, gn:Class, gn:Code, owl:Class, owl:DatatypeProperty, owl:ObjectProperty, owl:Ontology, owl:Restriction, owl:SymmetricProperty, owl:TransitiveProperty ┆ (untyped), owl:Class                                                        │
│ skos:notation                                    ┆ 690  ┆ gn:Code                                                                                                                                                                              ┆ xsd:string                                                                  │
│ skos:inScheme                                    ┆ 689  ┆ gn:Code                                                                                                                                                                              ┆ gn:Class                                                                    │
│ rdfs:comment                                     ┆ 35   ┆ gn:Class, owl:Class, owl:DatatypeProperty, owl:ObjectProperty, owl:Ontology, owl:SymmetricProperty, owl:TransitiveProperty                                                           ┆ rdf:langString, xsd:string                                                  │
│ rdfs:label                                       ┆ 34   ┆ owl:Class, owl:DatatypeProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty                                                                                   ┆ rdf:langString, xsd:string                                                  │
│ owl:deprecated                                   ┆ 23   ┆ gn:Code                                                                                                                                                                              ┆ xsd:boolean                                                                 │
│ rdfs:domain                                      ┆ 23   ┆ owl:DatatypeProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty                                                                                              ┆ owl:Class                                                                   │
│ skos:historyNote                                 ┆ 21   ┆ gn:Code, owl:Class, owl:DatatypeProperty                                                                                                                                             ┆ rdf:langString                                                              │
│ rdfs:subClassOf                                  ┆ 18   ┆ owl:Class                                                                                                                                                                            ┆ (untyped), owl:Class, owl:Restriction                                       │
│ rdfs:range                                       ┆ 16   ┆ owl:DatatypeProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty                                                                                              ┆ (untyped), owl:Class, owl:Restriction                                       │
│ owl:onProperty                                   ┆ 16   ┆ owl:Restriction                                                                                                                                                                      ┆ owl:DatatypeProperty, owl:ObjectProperty                                    │
│ rdfs:subPropertyOf                               ┆ 11   ┆ owl:DatatypeProperty, owl:ObjectProperty                                                                                                                                             ┆ (untyped), owl:DatatypeProperty, owl:ObjectProperty, owl:TransitiveProperty │
│ owl:maxCardinality                               ┆ 6    ┆ owl:Restriction                                                                                                                                                                      ┆ xsd:nonNegativeInteger                                                      │
│ owl:hasValue                                     ┆ 5    ┆ owl:Restriction                                                                                                                                                                      ┆ gn:Code                                                                     │
│ owl:cardinality                                  ┆ 4    ┆ owl:Restriction                                                                                                                                                                      ┆ xsd:nonNegativeInteger                                                      │
│ dcterms:contributor                              ┆ 4    ┆ owl:Ontology                                                                                                                                                                         ┆ xsd:string                                                                  │
│ rdfs:seeAlso                                     ┆ 3    ┆ owl:Class, owl:DatatypeProperty                                                                                                                                                      ┆ (untyped)                                                                   │
│ rdf:first                                        ┆ 2    ┆ (untyped)                                                                                                                                                                            ┆ (untyped), owl:ObjectProperty                                               │
│ foaf:name                                        ┆ 2    ┆ foaf:Organization, foaf:Person                                                                                                                                                       ┆ xsd:string                                                                  │
│ rdf:rest                                         ┆ 2    ┆ (untyped)                                                                                                                                                                            ┆ (untyped)                                                                   │
│ foaf:homepage                                    ┆ 2    ┆ foaf:Organization, owl:Ontology                                                                                                                                                      ┆ (untyped)                                                                   │
│ owl:imports                                      ┆ 2    ┆ owl:Ontology                                                                                                                                                                         ┆ (untyped)                                                                   │
│ vann:preferredNamespaceUri                       ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ xsd:string                                                                  │
│ owl:priorVersion                                 ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ (untyped)                                                                   │
│ <http://id.loc.gov/vocabulary/relators/dtm>      ┆ 1    ┆ foaf:Organization                                                                                                                                                                    ┆ foaf:Person                                                                 │
│ rdfs:isDefinedBy                                 ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ (untyped)                                                                   │
│ dcterms:publisher                                ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ foaf:Organization                                                           │
│ owl:propertyChainAxiom                           ┆ 1    ┆ owl:ObjectProperty                                                                                                                                                                   ┆ (untyped)                                                                   │
│ <http://www.w3.org/ns/adms#relatedDocumentation> ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ (untyped)                                                                   │
│ dcterms:issued                                   ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ xsd:string                                                                  │
│ owl:versionInfo                                  ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ rdf:langString                                                              │
│ dcterms:title                                    ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ rdf:langString                                                              │
│ <https://creativecommons.org/ns#license>         ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ (untyped)                                                                   │
│ owl:someValuesFrom                               ┆ 1    ┆ owl:Restriction                                                                                                                                                                      ┆ (untyped)                                                                   │
│ vann:preferredNamespacePrefix                    ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ xsd:string                                                                  │
│ owl:equivalentClass                              ┆ 1    ┆ owl:Class                                                                                                                                                                            ┆ (untyped)                                                                   │
│ dcterms:creator                                  ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ xsd:string                                                                  │
│ dcterms:modified                                 ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ xsd:string                                                                  │
│ dcterms:description                              ┆ 1    ┆ owl:Ontology                                                                                                                                                                         ┆ rdf:langString                                                              │
└──────────────────────────────────────────────────┴──────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┘

inspire-themes

┌────────────────────────────────────────────┬──────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────┐
│ property                                   ┆ uses ┆ domains                                                                                                          ┆ ranges                                                       │
│ ---                                        ┆ ---  ┆ ---                                                                                                              ┆ ---                                                          │
│ str                                        ┆ i64  ┆ str                                                                                                              ┆ str                                                          │
╞════════════════════════════════════════════╪══════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════╡
│ dcterms:format                             ┆ 217  ┆ (untyped), dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                        ┆ (untyped)                                                    │
│ dcterms:language                           ┆ 216  ┆ (untyped)                                                                                                        ┆ (untyped)                                                    │
│ rdfs:label                                 ┆ 216  ┆ (untyped)                                                                                                        ┆ rdf:langString                                               │
│ dcterms:hasFormat                          ┆ 216  ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ (untyped)                                                    │
│ <http://www.w3.org/ns/adms#prev>           ┆ 85   ┆ skos:Concept                                                                                                     ┆ (untyped)                                                    │
│ dcat:isPartOf                              ┆ 70   ┆ skos:Concept                                                                                                     ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme               │
│ rdf:type                                   ┆ 43   ┆ <http://www.w3.org/2006/vcard/ns#Kind>, dcat:Catalog, dcat:Dataset, foaf:Agent, skos:Concept, skos:ConceptScheme ┆ (untyped)                                                    │
│ dcterms:identifier                         ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ rdfs:Literal                                                 │
│ skos:definition                            ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ rdf:langString                                               │
│ dcterms:title                              ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ rdf:langString                                               │
│ dcterms:description                        ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ rdf:langString                                               │
│ <http://www.w3.org/ns/adms#last>           ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme │
│ foaf:primaryTopic                          ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme │
│ skos:inScheme                              ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme               │
│ owl:sameAs                                 ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ (untyped)                                                    │
│ dcterms:created                            ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ xsd:date                                                     │
│ skos:prefLabel                             ┆ 36   ┆ dcat:Catalog, dcat:Dataset, skos:Concept, skos:ConceptScheme                                                     ┆ rdf:langString                                               │
│ skos:hasTopConcept                         ┆ 35   ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ skos:Concept                                                 │
│ rdfs:isDefinedBy                           ┆ 35   ┆ skos:Concept                                                                                                     ┆ (untyped)                                                    │
│ dcterms:hasPart                            ┆ 35   ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ skos:Concept                                                 │
│ <http://www.w3.org/ns/adms#status>         ┆ 35   ┆ skos:Concept                                                                                                     ┆ (untyped)                                                    │
│ skos:topConceptOf                          ┆ 35   ┆ skos:Concept                                                                                                     ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme               │
│ vann:usageNote                             ┆ 34   ┆ skos:Concept                                                                                                     ┆ rdf:langString                                               │
│ foaf:name                                  ┆ 3    ┆ foaf:Agent                                                                                                       ┆ rdf:langString                                               │
│ <http://www.w3.org/2006/vcard/ns#hasEmail> ┆ 1    ┆ <http://www.w3.org/2006/vcard/ns#Kind>                                                                           ┆ (untyped)                                                    │
│ dcterms:accrualPeriodicity                 ┆ 1    ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ (untyped)                                                    │
│ <http://www.w3.org/2006/vcard/ns#fn>       ┆ 1    ┆ <http://www.w3.org/2006/vcard/ns#Kind>                                                                           ┆ rdf:langString                                               │
│ dcterms:rightsHolder                       ┆ 1    ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ foaf:Agent                                                   │
│ dcat:contactPoint                          ┆ 1    ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ <http://www.w3.org/2006/vcard/ns#Kind>                       │
│ dcterms:creator                            ┆ 1    ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ foaf:Agent                                                   │
│ dcterms:publisher                          ┆ 1    ┆ dcat:Catalog, dcat:Dataset, skos:ConceptScheme                                                                   ┆ foaf:Agent                                                   │
└────────────────────────────────────────────┴──────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────┘

iptc-media-topics

┌─────────────────────────────────────────────────────┬──────┬──────────────────────────────────┬────────────────────┐
│ property                                            ┆ uses ┆ domains                          ┆ ranges             │
│ ---                                                 ┆ ---  ┆ ---                              ┆ ---                │
│ str                                                 ┆ i64  ┆ str                              ┆ str                │
╞═════════════════════════════════════════════════════╪══════╪══════════════════════════════════╪════════════════════╡
│ skos:exactMatch                                     ┆ 2187 ┆ skos:Concept                     ┆ (untyped)          │
│ skos:prefLabel                                      ┆ 1394 ┆ skos:Concept, skos:ConceptScheme ┆ rdf:langString     │
│ skos:definition                                     ┆ 1394 ┆ skos:Concept, skos:ConceptScheme ┆ rdf:langString     │
│ rdf:type                                            ┆ 1394 ┆ skos:Concept, skos:ConceptScheme ┆ (untyped)          │
│ dcterms:modified                                    ┆ 1393 ┆ skos:Concept                     ┆ xsd:dateTime       │
│ <http://cv.iptc.org/newscodes/ikos/modified>        ┆ 1393 ┆ skos:Concept                     ┆ xsd:dateTime       │
│ <http://cv.iptc.org/newscodes/ikos/created>         ┆ 1393 ┆ skos:Concept                     ┆ xsd:dateTime       │
│ skos:inScheme                                       ┆ 1393 ┆ skos:Concept                     ┆ skos:ConceptScheme │
│ dcterms:created                                     ┆ 1393 ┆ skos:Concept                     ┆ xsd:dateTime       │
│ skos:narrower                                       ┆ 1376 ┆ skos:Concept                     ┆ skos:Concept       │
│ skos:broader                                        ┆ 1376 ┆ skos:Concept                     ┆ skos:Concept       │
│ <http://cv.iptc.org/newscodes/ikos/retired>         ┆ 308  ┆ skos:Concept                     ┆ xsd:dateTime       │
│ skos:broadMatch                                     ┆ 206  ┆ skos:Concept                     ┆ (untyped)          │
│ skos:changeNote                                     ┆ 177  ┆ skos:Concept                     ┆ rdf:langString     │
│ skos:note                                           ┆ 81   ┆ skos:Concept, skos:ConceptScheme ┆ rdf:langString     │
│ skos:closeMatch                                     ┆ 45   ┆ skos:Concept                     ┆ (untyped)          │
│ <http://cv.iptc.org/newscodes/ikos/hasFacet>        ┆ 43   ┆ skos:Concept                     ┆ (untyped)          │
│ skos:hasTopConcept                                  ┆ 17   ┆ skos:ConceptScheme               ┆ skos:Concept       │
│ skos:editorialNote                                  ┆ 2    ┆ skos:Concept                     ┆ rdf:langString     │
│ <http://cv.iptc.org/newscodes/ikos/dateReleased>    ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:dateTime       │
│ dcterms:rightsHolder                                ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
│ dcterms:dateSubmitted                               ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:dateTime       │
│ <http://cv.iptc.org/newscodes/ikos/licenceLink>     ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
│ <http://cv.iptc.org/newscodes/ikos/prefSchemeAlias> ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
│ <http://cv.iptc.org/newscodes/ikos/authority>       ┆ 1    ┆ skos:ConceptScheme               ┆ xsd:string         │
└─────────────────────────────────────────────────────┴──────┴──────────────────────────────────┴────────────────────┘

loc-genre-form

┌────────────────────┬───────┬──────────────────────────────────────────┬───────────────────────────────────────┐
│ property           ┆ uses  ┆ domains                                  ┆ ranges                                │
│ ---                ┆ ---   ┆ ---                                      ┆ ---                                   │
│ str                ┆ i64   ┆ str                                      ┆ str                                   │
╞════════════════════╪═══════╪══════════════════════════════════════════╪═══════════════════════════════════════╡
│ rdf:type           ┆ 14739 ┆ cs:ChangeSet, skos:Concept, skosxl:Label ┆ (untyped)                             │
│ skosxl:literalForm ┆ 6314  ┆ skosxl:Label                             ┆ rdf:langString                        │
│ skos:altLabel      ┆ 6121  ┆ skos:Concept                             ┆ rdf:langString                        │
│ skosxl:altLabel    ┆ 6121  ┆ skos:Concept                             ┆ skosxl:Label                          │
│ skos:changeNote    ┆ 5933  ┆ skos:Concept, skosxl:Label               ┆ cs:ChangeSet, rdf:langString          │
│ cs:creatorName     ┆ 5740  ┆ cs:ChangeSet                             ┆ (untyped)                             │
│ cs:createdDate     ┆ 5740  ┆ cs:ChangeSet                             ┆ xsd:dateTime                          │
│ cs:changeReason    ┆ 5740  ┆ cs:ChangeSet                             ┆ xsd:string                            │
│ cs:subjectOfChange ┆ 5740  ┆ cs:ChangeSet                             ┆ skos:Concept, skosxl:Label            │
│ skos:broader       ┆ 3405  ┆ skos:Concept                             ┆ skos:Concept                          │
│ skos:narrower      ┆ 3401  ┆ skos:Concept                             ┆ skos:Concept                          │
│ skos:prefLabel     ┆ 2685  ┆ skos:Concept                             ┆ rdf:langString                        │
│ skos:inScheme      ┆ 2681  ┆ skos:Concept                             ┆ (untyped)                             │
│ skos:note          ┆ 1214  ┆ skos:Concept, skosxl:Label               ┆ xsd:string                            │
│ skos:historyNote   ┆ 278   ┆ skos:Concept, skosxl:Label               ┆ xsd:string                            │
│ rdfs:seeAlso       ┆ 253   ┆ skosxl:Label                             ┆ (untyped), skos:Concept, skosxl:Label │
│ skos:related       ┆ 212   ┆ skos:Concept                             ┆ skos:Concept                          │
│ skos:example       ┆ 203   ┆ skos:Concept, skosxl:Label               ┆ xsd:string                            │
└────────────────────┴───────┴──────────────────────────────────────────┴───────────────────────────────────────┘

loc-relators

┌────────────────────┬──────┬────────────────────────────┬─────────────────────────┐
│ property           ┆ uses ┆ domains                    ┆ ranges                  │
│ ---                ┆ ---  ┆ ---                        ┆ ---                     │
│ str                ┆ i64  ┆ str                        ┆ str                     │
╞════════════════════╪══════╪════════════════════════════╪═════════════════════════╡
│ rdf:type           ┆ 325  ┆ skos:Concept, skosxl:Label ┆ (untyped)               │
│ skos:inScheme      ┆ 271  ┆ (untyped), skos:Concept    ┆ (untyped)               │
│ skos:notation      ┆ 271  ┆ (untyped), skos:Concept    ┆ xsd:string              │
│ skos:definition    ┆ 268  ┆ skos:Concept               ┆ rdf:langString          │
│ skos:prefLabel     ┆ 268  ┆ skos:Concept               ┆ xsd:string              │
│ skos:editorial     ┆ 75   ┆ (untyped), skos:Concept    ┆ rdf:langString          │
│ skos:broader       ┆ 64   ┆ skos:Concept               ┆ (untyped), skos:Concept │
│ skos:narrower      ┆ 63   ┆ skos:Concept               ┆ skos:Concept            │
│ skos:altLabel      ┆ 57   ┆ (untyped), skos:Concept    ┆ xsd:string              │
│ skosxl:literalForm ┆ 57   ┆ skosxl:Label               ┆ xsd:string              │
│ skosxl:altLabel    ┆ 57   ┆ (untyped), skos:Concept    ┆ skosxl:Label            │
│ skos:hiddenLabel   ┆ 3    ┆ (untyped)                  ┆ xsd:string              │
└────────────────────┴──────┴────────────────────────────┴─────────────────────────┘

nerc-p06-units

┌──────────────────────────────────────────────────────────┬───────┬───────────────────────────────┬────────────────────────────┐
│ property                                                 ┆ uses  ┆ domains                       ┆ ranges                     │
│ ---                                                      ┆ ---   ┆ ---                           ┆ ---                        │
│ str                                                      ┆ i64   ┆ str                           ┆ str                        │
╞══════════════════════════════════════════════════════════╪═══════╪═══════════════════════════════╪════════════════════════════╡
│ skos:related                                             ┆ 58090 ┆ skos:Concept                  ┆ (untyped)                  │
│ rdf:type                                                 ┆ 411   ┆ skos:Collection, skos:Concept ┆ (untyped)                  │
│ skos:prefLabel                                           ┆ 411   ┆ skos:Collection, skos:Concept ┆ rdf:langString, xsd:string │
│ owl:versionInfo                                          ┆ 411   ┆ skos:Collection, skos:Concept ┆ xsd:string                 │
│ dcterms:date                                             ┆ 411   ┆ skos:Collection, skos:Concept ┆ xsd:string                 │
│ skos:altLabel                                            ┆ 411   ┆ skos:Collection, skos:Concept ┆ xsd:string                 │
│ void:inDataset                                           ┆ 410   ┆ skos:Concept                  ┆ (untyped)                  │
│ dcterms:identifier                                       ┆ 410   ┆ skos:Concept                  ┆ xsd:string                 │
│ <http://purl.org/pav/hasCurrentVersion>                  ┆ 410   ┆ skos:Concept                  ┆ (untyped)                  │
│ skos:notation                                            ┆ 410   ┆ skos:Concept                  ┆ xsd:string                 │
│ dc:identifier                                            ┆ 410   ┆ skos:Concept                  ┆ xsd:string                 │
│ owl:deprecated                                           ┆ 410   ┆ skos:Concept                  ┆ xsd:string                 │
│ <http://purl.org/pav/version>                            ┆ 410   ┆ skos:Concept                  ┆ xsd:string                 │
│ <http://purl.org/pav/authoredOn>                         ┆ 410   ┆ skos:Concept                  ┆ xsd:string                 │
│ skos:member                                              ┆ 410   ┆ skos:Collection               ┆ skos:Concept               │
│ skos:definition                                          ┆ 410   ┆ skos:Concept                  ┆ rdf:langString, xsd:string │
│ skos:note                                                ┆ 410   ┆ skos:Concept                  ┆ rdf:langString             │
│ owl:sameAs                                               ┆ 389   ┆ skos:Concept                  ┆ (untyped), skos:Concept    │
│ skos:broader                                             ┆ 244   ┆ skos:Concept                  ┆ (untyped)                  │
│ <http://purl.org/pav/hasVersion>                         ┆ 177   ┆ skos:Concept                  ┆ (untyped)                  │
│ skos:inScheme                                            ┆ 46    ┆ skos:Concept                  ┆ (untyped)                  │
│ dcterms:replaces                                         ┆ 4     ┆ skos:Concept                  ┆ skos:Concept               │
│ dcterms:isReplacedBy                                     ┆ 4     ┆ skos:Concept                  ┆ skos:Concept               │
│ dcterms:license                                          ┆ 1     ┆ skos:Collection               ┆ (untyped)                  │
│ rdfs:comment                                             ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ dcterms:publisher                                        ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ dcterms:alternative                                      ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ dcterms:creator                                          ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ <http://www.isotc211.org/schemas/grg/RE_RegisterOwner>   ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ dcterms:title                                            ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ <http://www.isotc211.org/schemas/grg/RE_RegisterManager> ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
│ rdfs:seeAlso                                             ┆ 1     ┆ skos:Collection               ┆ (untyped)                  │
│ dcterms:description                                      ┆ 1     ┆ skos:Collection               ┆ xsd:string                 │
└──────────────────────────────────────────────────────────┴───────┴───────────────────────────────┴────────────────────────────┘

physh

┌───────────────────────────┬──────┬────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────┐
│ property                  ┆ uses ┆ domains                                                                        ┆ ranges                                   │
│ ---                       ┆ ---  ┆ ---                                                                            ┆ ---                                      │
│ str                       ┆ i64  ┆ str                                                                            ┆ str                                      │
╞═══════════════════════════╪══════╪════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════╡
│ rdf:type                  ┆ 4506 ┆ physh:Concept, physh:Discipline, physh:Facet, skos:Concept, skos:ConceptScheme ┆ (untyped)                                │
│ physh:prefLabel           ┆ 3910 ┆ physh:Concept, physh:Discipline, physh:Facet, skos:Concept, skos:ConceptScheme ┆ rdf:langString                           │
│ skos:prefLabel            ┆ 3891 ┆ physh:Concept, physh:Facet, skos:Concept                                       ┆ rdf:langString                           │
│ skos:broader              ┆ 3682 ┆ physh:Concept, physh:Facet, skos:Concept                                       ┆ physh:Concept, physh:Facet, skos:Concept │
│ skos:narrower             ┆ 3682 ┆ physh:Concept, physh:Facet, skos:Concept                                       ┆ physh:Concept, physh:Facet, skos:Concept │
│ skos:related              ┆ 783  ┆ physh:Concept, skos:Concept                                                    ┆ physh:Concept, skos:Concept              │
│ physh:inDiscipline        ┆ 672  ┆ physh:Concept, skos:Concept                                                    ┆ physh:Discipline, skos:ConceptScheme     │
│ physh:hasConcept          ┆ 672  ┆ physh:Discipline, skos:ConceptScheme                                           ┆ physh:Concept, skos:Concept              │
│ skos:altLabel             ┆ 633  ┆ physh:Concept, skos:Concept                                                    ┆ rdf:langString                           │
│ physh:contains            ┆ 560  ┆ physh:Facet, skos:Concept                                                      ┆ physh:Concept, skos:Concept              │
│ physh:inFacet             ┆ 560  ┆ physh:Concept, skos:Concept                                                    ┆ physh:Facet, skos:Concept                │
│ physh:usesFacet           ┆ 78   ┆ physh:Discipline, skos:ConceptScheme                                           ┆ physh:Facet, skos:Concept                │
│ physh:usedByDiscipline    ┆ 78   ┆ physh:Facet, skos:Concept                                                      ┆ physh:Discipline, skos:ConceptScheme     │
│ skos:scopeNote            ┆ 47   ┆ physh:Concept, skos:Concept                                                    ┆ rdf:langString                           │
│ dcterms:description       ┆ 19   ┆ physh:Discipline, skos:ConceptScheme                                           ┆ rdf:langString                           │
│ dcterms:subject           ┆ 19   ┆ physh:Discipline, skos:ConceptScheme                                           ┆ rdf:langString                           │
│ dcterms:title             ┆ 19   ┆ physh:Discipline, skos:ConceptScheme                                           ┆ rdf:langString                           │
│ dcterms:publisher         ┆ 19   ┆ physh:Discipline, skos:ConceptScheme                                           ┆ (untyped)                                │
│ physh:deprecated          ┆ 9    ┆ physh:Concept, physh:Discipline, skos:Concept, skos:ConceptScheme              ┆ xsd:boolean                              │
│ skos:hiddenLabel          ┆ 7    ┆ skos:Concept                                                                   ┆ rdf:langString                           │
│ physh:excludeFromIndexing ┆ 5    ┆ physh:Concept, physh:Facet, skos:Concept                                       ┆ xsd:boolean                              │
│ skos:hasTopConcept        ┆ 5    ┆ physh:Discipline, skos:ConceptScheme                                           ┆ physh:Facet, skos:Concept                │
│ skos:topConceptOf         ┆ 5    ┆ physh:Facet, skos:Concept                                                      ┆ physh:Discipline, skos:ConceptScheme     │
│ skos:example              ┆ 2    ┆ physh:Concept, skos:Concept                                                    ┆ rdf:langString                           │
└───────────────────────────┴──────┴────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────┘

stw-economics

┌─────────────────────────────────────────────────┬───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ property                                        ┆ uses  ┆ domains                                                                                                                                                                                                                                                                                        ┆ ranges                                                                                                                                   │
│ ---                                             ┆ ---   ┆ ---                                                                                                                                                                                                                                                                                            ┆ ---                                                                                                                                      │
│ str                                             ┆ i64   ┆ str                                                                                                                                                                                                                                                                                            ┆ str                                                                                                                                      │
╞═════════════════════════════════════════════════╪═══════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ skos:altLabel                                   ┆ 20451 ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ rdf:langString                                                                                                                           │
│ rdf:type                                        ┆ 15788 ┆ owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty, owl:ObjectProperty, owl:Ontology, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property, skos:Concept, skos:ConceptScheme, void:Dataset, zbwext:Descriptor, zbwext:Thsys ┆ (untyped), owl:Class                                                                                                                     │
│ skos:related                                    ┆ 14522 ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ skos:Concept, zbwext:Descriptor                                                                                                          │
│ skos:narrower                                   ┆ 14351 ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                  ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                            │
│ skos:broader                                    ┆ 14351 ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                  ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                            │
│ skos:prefLabel                                  ┆ 13394 ┆ skos:Concept, skos:ConceptScheme, void:Dataset, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                ┆ rdf:langString                                                                                                                           │
│ skos:inScheme                                   ┆ 7845  ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                  ┆ skos:ConceptScheme, void:Dataset                                                                                                         │
│ <http://purl.org/ontology/gbv/gvkppn>           ┆ 6198  ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ xsd:string                                                                                                                               │
│ rdfs:label                                      ┆ 3352  ┆ owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property, skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                 ┆ rdf:langString                                                                                                                           │
│ skos:historyNote                                ┆ 2328  ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                  ┆ rdf:langString                                                                                                                           │
│ zbwext:altLabelNarrower                         ┆ 1450  ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ rdf:langString                                                                                                                           │
│ skos:scopeNote                                  ┆ 1240  ┆ owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:ObjectProperty, owl:TransitiveProperty, rdf:Property, skos:Concept, zbwext:Descriptor                                                                                                                                             ┆ rdf:langString                                                                                                                           │
│ owl:deprecated                                  ┆ 1149  ┆ skos:Concept, zbwext:Descriptor, zbwext:Thsys                                                                                                                                                                                                                                                  ┆ xsd:boolean                                                                                                                              │
│ dcterms:isReplacedBy                            ┆ 1019  ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ skos:Concept, zbwext:Descriptor                                                                                                          │
│ rdfs:seeAlso                                    ┆ 693   ┆ (untyped), owl:Ontology                                                                                                                                                                                                                                                                        ┆ (untyped), skos:Concept, zbwext:Descriptor                                                                                               │
│ rdf:value                                       ┆ 692   ┆ (untyped)                                                                                                                                                                                                                                                                                      ┆ rdf:langString                                                                                                                           │
│ zbwext:useInsteadNote                           ┆ 692   ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ (untyped)                                                                                                                                │
│ skos:notation                                   ┆ 498   ┆ skos:Concept, zbwext:Thsys                                                                                                                                                                                                                                                                     ┆ xsd:string                                                                                                                               │
│ zbwext:altLabelRelated                          ┆ 390   ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ rdf:langString                                                                                                                           │
│ rdfs:isDefinedBy                                ┆ 58    ┆ owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property                                                                                                ┆ (untyped), owl:Ontology                                                                                                                  │
│ skos:definition                                 ┆ 58    ┆ owl:AnnotationProperty, owl:Class, owl:DatatypeProperty, owl:FunctionalProperty, owl:InverseFunctionalProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property                                                                                                ┆ rdf:langString, xsd:string                                                                                                               │
│ rdfs:subPropertyOf                              ┆ 31    ┆ owl:AnnotationProperty, owl:FunctionalProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property                                                                                                                                                                ┆ (untyped), owl:AnnotationProperty, owl:DatatypeProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property │
│ rdfs:comment                                    ┆ 18    ┆ owl:AnnotationProperty, owl:Class, owl:FunctionalProperty, owl:ObjectProperty, owl:SymmetricProperty, owl:TransitiveProperty, rdf:Property                                                                                                                                                     ┆ rdf:langString                                                                                                                           │
│ skos:hiddenLabel                                ┆ 10    ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ rdf:langString                                                                                                                           │
│ skos:editorialNote                              ┆ 9     ┆ skos:Concept, zbwext:Descriptor                                                                                                                                                                                                                                                                ┆ rdf:langString                                                                                                                           │
│ rdfs:subClassOf                                 ┆ 8     ┆ owl:Class                                                                                                                                                                                                                                                                                      ┆ owl:Class                                                                                                                                │
│ owl:inverseOf                                   ┆ 8     ┆ owl:ObjectProperty, owl:TransitiveProperty, rdf:Property                                                                                                                                                                                                                                       ┆ owl:ObjectProperty, owl:TransitiveProperty, rdf:Property                                                                                 │
│ skos:hasTopConcept                              ┆ 7     ┆ skos:ConceptScheme, void:Dataset                                                                                                                                                                                                                                                               ┆ skos:Concept, zbwext:Thsys                                                                                                               │
│ skos:topConceptOf                               ┆ 7     ┆ skos:Concept, zbwext:Thsys                                                                                                                                                                                                                                                                     ┆ skos:ConceptScheme, void:Dataset                                                                                                         │
│ rdfs:range                                      ┆ 6     ┆ owl:FunctionalProperty, owl:ObjectProperty, rdf:Property                                                                                                                                                                                                                                       ┆ (untyped), owl:Class                                                                                                                     │
│ void:vocabulary                                 ┆ 5     ┆ skos:ConceptScheme, void:Dataset                                                                                                                                                                                                                                                               ┆ (untyped)                                                                                                                                │
│ dc:creator                                      ┆ 5     ┆ (untyped), skos:ConceptScheme, void:Dataset                                                                                                                                                                                                                                                    ┆ rdf:langString, xsd:string                                                                                                               │
│ rdfs:domain                                     ┆ 5     ┆ owl:FunctionalProperty, owl:ObjectProperty, rdf:Property                                                                                                                                                                                                                                       ┆ owl:Class                                                                                                                                │
│ void:feature                                    ┆ 4     ┆ skos:ConceptScheme, void:Dataset                                                                                                                                                                                                                                                               ┆ (untyped)                                                                                                                                │
│ dcterms:title                                   ┆ 3     ┆ owl:Ontology, skos:ConceptScheme, void:Dataset                                                                                                                                                                                                                                                 ┆ rdf:langString                                                                                                                           │

uat-astronomy

┌─────────────────────┬──────┬──────────────────────────────────┬────────────────────────────┐
│ property            ┆ uses ┆ domains                          ┆ ranges                     │
│ ---                 ┆ ---  ┆ ---                              ┆ ---                        │
│ str                 ┆ i64  ┆ str                              ┆ str                        │
╞═════════════════════╪══════╪══════════════════════════════════╪════════════════════════════╡
│ skos:narrower       ┆ 2693 ┆ skos:Concept                     ┆ skos:Concept               │
│ skos:broader        ┆ 2693 ┆ skos:Concept                     ┆ skos:Concept               │
│ dcterms:modified    ┆ 2414 ┆ skos:Concept, skos:ConceptScheme ┆ xsd:dateTime               │
│ rdf:type            ┆ 2412 ┆ skos:Concept, skos:ConceptScheme ┆ (untyped)                  │
│ skos:prefLabel      ┆ 2354 ┆ skos:Concept                     ┆ rdf:langString             │
│ skos:altLabel       ┆ 1839 ┆ skos:Concept                     ┆ rdf:langString             │
│ dcterms:contributor ┆ 1683 ┆ skos:Concept, skos:ConceptScheme ┆ (untyped)                  │
│ dcterms:created     ┆ 1655 ┆ (untyped), skos:Concept          ┆ xsd:dateTime               │
│ dcterms:creator     ┆ 1655 ┆ (untyped), skos:Concept          ┆ (untyped)                  │
│ dcterms:title       ┆ 1086 ┆ (untyped), skos:ConceptScheme    ┆ rdf:langString, xsd:string │
│ rdfs:comment        ┆ 1085 ┆ (untyped)                        ┆ xsd:string                 │
│ skos:editorialNote  ┆ 867  ┆ skos:Concept                     ┆ (untyped), rdf:langString  │
│ skos:definition     ┆ 859  ┆ skos:Concept                     ┆ rdf:langString             │
│ skos:related        ┆ 696  ┆ skos:Concept                     ┆ skos:Concept               │
│ skos:changeNote     ┆ 114  ┆ skos:Concept                     ┆ (untyped)                  │
│ owl:deprecated      ┆ 99   ┆ skos:Concept                     ┆ xsd:boolean                │
│ rdfs:label          ┆ 99   ┆ skos:Concept                     ┆ rdf:langString             │
│ skos:scopeNote      ┆ 66   ┆ skos:Concept                     ┆ rdf:langString             │
│ skos:example        ┆ 40   ┆ skos:Concept                     ┆ rdf:langString             │
│ skos:hasTopConcept  ┆ 11   ┆ skos:ConceptScheme               ┆ skos:Concept               │
│ skos:topConceptOf   ┆ 11   ┆ skos:Concept                     ┆ skos:ConceptScheme         │
│ dcterms:publisher   ┆ 1    ┆ skos:ConceptScheme               ┆ (untyped)                  │
│ dcterms:subject     ┆ 1    ┆ skos:ConceptScheme               ┆ rdf:langString             │
│ dcterms:description ┆ 1    ┆ skos:ConceptScheme               ┆ rdf:langString             │
└─────────────────────┴──────┴──────────────────────────────────┴────────────────────────────┘

unesco-thesaurus

┌──────────────────────┬───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────┐
│ property             ┆ uses  ┆ domains                                                                                                                   ┆ ranges                                                                      │
│ ---                  ┆ ---   ┆ ---                                                                                                                       ┆ ---                                                                         │
│ str                  ┆ i64   ┆ str                                                                                                                       ┆ str                                                                         │
╞══════════════════════╪═══════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════╡
│ skos:prefLabel       ┆ 22939 ┆ iso-thes:ConceptGroup, skos:Collection, skos:Concept, skos:ConceptScheme, unesco:Domain, unesco:MicroThesaurus            ┆ rdf:langString                                                              │
│ skos:altLabel        ┆ 21071 ┆ iso-thes:ConceptGroup, skos:Collection, skos:Concept, unesco:MicroThesaurus                                               ┆ rdf:langString                                                              │
│ skos:related         ┆ 12583 ┆ skos:Concept                                                                                                              ┆ skos:Concept                                                                │
│ skos:hiddenLabel     ┆ 11470 ┆ iso-thes:ConceptGroup, skos:Collection, skos:Concept, unesco:Domain, unesco:MicroThesaurus                                ┆ rdf:langString                                                              │
│ rdf:type             ┆ 4786  ┆ iso-thes:ConceptGroup, skos:Collection, skos:Concept, skos:ConceptScheme, unesco:Domain, unesco:MicroThesaurus            ┆ (untyped)                                                                   │
│ dcterms:modified     ┆ 4597  ┆ (untyped), iso-thes:ConceptGroup, skos:Collection, skos:Concept, skos:ConceptScheme, unesco:Domain, unesco:MicroThesaurus ┆ xsd:date, xsd:dateTime                                                      │
│ skos:inScheme        ┆ 4595  ┆ iso-thes:ConceptGroup, skos:Collection, skos:Concept, unesco:Domain, unesco:MicroThesaurus                                ┆ skos:ConceptScheme                                                          │
│ skos:member          ┆ 4588  ┆ iso-thes:ConceptGroup, skos:Collection, unesco:Domain, unesco:MicroThesaurus                                              ┆ iso-thes:ConceptGroup, skos:Collection, skos:Concept, unesco:MicroThesaurus │
│ skos:narrower        ┆ 4343  ┆ skos:Concept                                                                                                              ┆ skos:Concept                                                                │
│ skos:broader         ┆ 4343  ┆ skos:Concept                                                                                                              ┆ skos:Concept                                                                │
│ skos:scopeNote       ┆ 3301  ┆ skos:Concept                                                                                                              ┆ rdf:langString                                                              │
│ skos:topConceptOf    ┆ 585   ┆ skos:Concept                                                                                                              ┆ skos:ConceptScheme                                                          │
│ dcterms:created      ┆ 181   ┆ (untyped), skos:Concept, skos:ConceptScheme                                                                               ┆ xsd:date, xsd:dateTime                                                      │
│ skos:notation        ┆ 95    ┆ iso-thes:ConceptGroup, skos:Collection, unesco:Domain, unesco:MicroThesaurus                                              ┆ xsd:string                                                                  │
│ iso-thes:superGroup  ┆ 88    ┆ iso-thes:ConceptGroup, skos:Collection, unesco:MicroThesaurus                                                             ┆ iso-thes:ConceptGroup, skos:Collection, unesco:Domain                       │
│ iso-thes:subGroup    ┆ 88    ┆ iso-thes:ConceptGroup, skos:Collection, unesco:Domain                                                                     ┆ iso-thes:ConceptGroup, skos:Collection, unesco:MicroThesaurus               │
│ skos:note            ┆ 11    ┆ skos:Concept                                                                                                              ┆ rdf:langString                                                              │
│ dcterms:subject      ┆ 7     ┆ skos:ConceptScheme                                                                                                        ┆ (untyped)                                                                   │
│ dc:subject           ┆ 7     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:description  ┆ 5     ┆ skos:ConceptScheme                                                                                                        ┆ rdf:langString                                                              │
│ dcterms:language     ┆ 5     ┆ skos:ConceptScheme                                                                                                        ┆ (untyped)                                                                   │
│ rdf:value            ┆ 4     ┆ (untyped)                                                                                                                 ┆ rdf:langString                                                              │
│ dcterms:source       ┆ 3     ┆ (untyped), skos:ConceptScheme                                                                                             ┆ (untyped)                                                                   │
│ skos:definition      ┆ 2     ┆ skos:Concept                                                                                                              ┆ (untyped)                                                                   │
│ dcterms:identifier   ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:type         ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dc:creator           ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:isRequiredBy ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ (untyped)                                                                   │
│ skos:editorialNote   ┆ 1     ┆ skos:Concept                                                                                                              ┆ rdf:langString                                                              │
│ owl:imports          ┆ 1     ┆ (untyped)                                                                                                                 ┆ (untyped)                                                                   │
│ dcterms:conformsTo   ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:license      ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ (untyped)                                                                   │
│ dcterms:rights       ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:rightsHolder ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:format       ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ (untyped)                                                                   │
│ dc:contributor       ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dc:publisher         ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ xsd:string                                                                  │
│ dcterms:replaces     ┆ 1     ┆ skos:ConceptScheme                                                                                                        ┆ (untyped)                                                                   │
└──────────────────────┴───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┘